# Copyright (c) 2014 Kevin Bell. All rights reserved.
# See the file LICENSE.txt for copying permission.

- name: gather facts based on ec2 metadata
  ec2_facts:
- name: create derived facts based on ec2 facts
  set_fact:
    gridviz_hostname:
      "{{ hostvars[inventory_hostname]['ansible_ec2_public_hostname'] }}"
    django_env:
      GRIDVIZ_HOSTNAME:
        "{{ hostvars[inventory_hostname]['ansible_ec2_public_hostname'] }}"
      DJANGO_SETTINGS_MODULE: gridviz.settings.prod
      DB_USER: "{{ db_user }}"
      DB_PASS: "{{ db_pass }}"
      DJANGO_SECRET_KEY: "{{ django_secret_key }}"
- name: ensure required packages installed
  apt: name={{ item }} state=present
  with_items:
    - git
    - python-pip
    - python-dev
    - nodejs
    - npm
- name: ensure nodejs available as node
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
- name: checkout repo
  git: repo=https://github.com/bellkev/gridviz.git dest=/opt/gridviz
- name: ensure pip packages installed
  pip: requirements=/opt/gridviz/requirements.txt
- name: ensure bower and grunt available
  npm: global=yes name={{ item }}
  with_items:
    - bower
    - grunt-cli
- name: ensure bower packages installed
  command: bower install --allow-root chdir=/opt/gridviz
- name: ensure npm packages installed
  command: npm install chdir=/opt/gridviz
- name: ensure less compiled
  command: grunt less chdir=/opt/gridviz
- name: ensure database exists
  mysql_db:
    name: gridviz
    state: present
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_pass }}"
- name: run django migrations and collectstatic
  django_manage: app_path=/opt/gridviz/django command={{ item }} settings=gridviz.settings.dev_uwsgi
  environment: django_env
  with_items:
    - migrate
    - collectstatic
# This task needs to use template because ini_file can't handle uwsgi's duplicate keys
- name: ensure uwsgi config file in place
  template: src=uwsgi_dev.ini dest=/etc/uwsgi/apps-available
- name: ensure uwsgi app enabled
  file: src=/etc/uwsgi/apps-available/uwsgi_dev.ini dest=/etc/uwsgi/apps-enabled/uwsgi_dev.ini state=link
- name: ensure nginx config file in place
  template: src=nginx_dev.conf dest=/etc/nginx/sites-available
- name: ensure nginx site enabled
  file: src=/etc/nginx/sites-available/nginx_dev.conf dest=/etc/nginx/sites-enabled/nginx_dev.conf state=link
# The following is necessary for uwsgi because it appears not to be running in emperor
# mode in the debian distribution init.d script
- name: check if uwsgi app already exists
  command: "[ -d /run/uwsgi/app/uwsgi_dev ]"
  ignore_errors: yes
  register: uwsgi_run_result
- name: ensure uwsgi restarted
  service: name=uwsgi state=restarted
  when: uwsgi_run_result.rc
- name: ensure services reloaded
  service: name={{ item }} state=reloaded
  with_items:
    - nginx
    - uwsgi
