language: python
python:
  - 2.7
install:
  - pip install https://github.com/django/django/archive/1.7b1.zip
  - pip install -r requirements.txt
  - npm install -g karma-cli bower
  - npm install
  - bower install
script:
  - coverage run --source=gridviz django/manage.py test gridviz
  - karma start angular/karma-coverage.conf.js --single-run
after_success:
  coveralls