# Copyright (c) 2014 Kevin Bell. All rights reserved.
# See the file LICENSE.txt for copying permission.

language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - npm install -g karma-cli bower
  - npm install
  - bower install
script:
  - python python_scripts/run_coverage.py run --rcfile=django/.coveragerc django/manage.py test gridviz
  - karma start angular/karma-coverage.conf.js --single-run
after_success:
  - node node_scripts/convert_lcov.js angular/coverage/PhantomJS*/lcov.info angular/coverage/coveralls.json
  - python python_scripts/merge_coveralls.py angular/coverage/coveralls.json