# Copyright (c) 2014 Kevin Bell. All rights reserved.
# See the file LICENSE.txt for copying permission.

---
- name: ensure mysql-server installed
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb
- name: ensure mysql service started
  service: name=mysql state=started