# Copyright (c) 2014 Kevin Bell. All rights reserved.
# See the file LICENSE.txt for copying permission.

---
- name: ensure nginx installed
  apt: name=nginx state=present
- name: ensure nginx service started
  service: name=nginx state=started