# Copyright (c) 2014 Kevin Bell. All rights reserved.
# See the file LICENSE.txt for copying permission.

---
- hosts: all
  remote_user: ubuntu
  sudo: yes
  tasks:
  # MySQL
  - name: ensure mysql installed
    apt: name={{ item }} state=present
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb
  - name: create database
    mysql_db: name=gridviz state=present
  # Nginx
  - name: ensure nginx installed
    apt: name=nginx state=present
  # uwsgi
  - name: ensure uwsgi installed
    apt: name=uwsgi state=present
  # app
  - ec2_facts:
  - name: ensure git installed
    apt: name=git state=present
  - name: checkout repo
    git: repo=https://github.com/bellkev/gridviz.git dest=/opt/gridviz
  - name: ensure pip installed
    apt: name=python-pip state=present
  - name: ensure python-dev installed
    apt: name=python-dev state=present
  - name: ensure pip packages installed
    pip: requirements=/opt/gridviz/requirements.txt
  - name: run django migrations
    django_manage: app_path=/opt/gridviz/django command=migrate settings=gridviz.settings.dev_uwsgi
    environment: {GRIDVIZ_HOSTNAME: "{{ hostvars[inventory_hostname]['ansible_ec2_public_hostname'] }}"}
