# Copyright (c) 2014 Kevin Bell. All rights reserved.
# See the file LICENSE.txt for copying permission.

---
- name: create an autoscaling group based on a launch configuration
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    role: gridviz-app-server
    keypair: aws-key-2
    instance_type: t1.micro
    group: ssh-http
    region: us-west-2
    azs: us-west-2a,us-west-2b,us-west-2c
  tasks:
  - name: lookup ami id
    ec2_ami_search: distro=ubuntu region={{ region }} release=trusty
    register: ubuntu_image
  # Note that launch configs cannot be updated -- only created or deleted
  - name: ensure launch config exists
    ec2_lc:
      name: prod_lc
      region: "{{ region }}"
      image_id: "{{ ubuntu_image.ami }}"
      key_name: "{{ keypair }}"
      security_groups: "{{ group }}"
      instance_type: "{{ instance_type }}"
      instance_profile_name: "{{ role }}"
      user_data: |
        #!/bin/bash
        apt-get install -y git python-setuptools python-dev
        git clone -b personal https://github.com/bellkev/ansible.git /opt/ansible
        (cd /opt/ansible && setup.py install)
        git clone https://github.com/bellkev/gridviz.git {{ gridviz_root }}
        ansible-playbook {{ gridviz_root }}/ansible/bootstrap.yml
  - name: ensure asg exists
    ec2_asg:
      name: prod_asg
      launch_config_name: prod_lc
      min_size: 1
      max_size: 1
      region: "{{ region }}"
      availability_zones: "{{ azs }}"
      state: present
