# Copyright (c) 2014 Kevin Bell. All rights reserved.
# See the file LICENSE.txt for copying permission.

---
- name: lookup ami id
  ec2_ami_search: distro=ubuntu region={{ region }} release=trusty
  register: ubuntu_image
- name: ensure one instance exists
  ec2:
    image: "{{ ubuntu_image.ami }}"
    instance_type: "{{ instance_type }}"
    instance_tags: "{{ count_tags }}"
    region: "{{ region }}"
    group: "{{ security_group }}"
    wait: yes
    exact_count: 1
    count_tag: "{{ count_tags }}"
    key_name: "{{ keypair }}"
  register: ec2_info
- name: add instance to in-memory hosts
  add_host: hostname={{ item.public_dns_name }} groupname=ec2_hosts
  with_items: ec2_info.tagged_instances
- name: wait for instances to listen on port 22
  wait_for: state=started host={{ item.public_dns_name }} port=22
  with_items: ec2_info.tagged_instances