# Copyright (c) 2014 Kevin Bell. All rights reserved.
# See the file LICENSE.txt for copying permission.

---
- name: ensure pip installed
  apt: name=python-pip state=present
- name: install from wheel
  pip:
    name: uwsgi
    extra_args: --find-links=http://gridviz-wheelhouse.s3-website-us-west-2.amazonaws.com --no-index
- name: ensure vassal directory in place
  file: path=/etc/uwsgi/ state=directory
- name: setup upstart
  copy: src=uwsgi.conf dest=/etc/init/
- name: ensure uwsgi service started
  service: name=uwsgi state=started
